_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 8
dataset:
    value:
        max_crops_per_utt: null
        min_frames_for_multi: 128
        segment_frames: 184
        stride_frames_train: 92
        stride_frames_valid: 92
        use_memmap_shapes: true
loss:
    value:
        alpha: 0.1
        beta: 0.0001
model_save_path:
    value: ./checkpoints
n_epochs:
    value: 100
n_files:
    value: null
num_workers:
    value: 4
preprocess:
    value:
        normalize: true
ref_mic_ind:
    value: 0
seed:
    value: 0
stft:
    value:
        center: true
        hop_length: 255
        n_fft: 510
        win_length: 510
wandb:
    value:
        enable: true
        project: lmfca-net
